"""Task-owned, bounded native GLM capability E2E under the unique controller.

No engine restart or model implementation modification. All generated bytes and
native metrics remain in the Run directory. A finite probe is not a capacity claim.
"""
import argparse,asyncio,fcntl,hashlib,json,os,re,signal,subprocess,sys,time
from owner_guard import start_watchdog
start_watchdog()
from pathlib import Path
from phase_runner import atomic_json,utc
from loadgen import execute

LOCK_ROOT=Path('/data/tiankuan/wio/glm52-pd')
BACKENDS=[{'id':'DP0','url':'http://172.16.10.166:9081'},{'id':'DP1','url':'http://172.16.10.167:9900'}]
ROUTER='http://127.0.0.1:8002'

def body(text,output=128,stream=True,completion=False,n=1):
    value={'model':'glm-52','max_tokens':output,'temperature':(.7 if n>1 else 0),'seed':20260930,'ignore_eos':True,'stream':stream,'n':n}
    if completion:value['prompt']=text
    else:value['messages']=[{'role':'user','content':text}]
    if stream:value['stream_options']={'include_usage':True}
    return value

async def main(root,run_id,reuse_local=None):
    import httpx
    root=Path(root);root.mkdir(exist_ok=False)
    owner=json.loads((LOCK_ROOT/'controller-owner.json').read_text())
    if owner['run_id']!=run_id or owner['status']!='running' or owner['owner']['boot_id']!=Path('/proc/sys/kernel/random/boot_id').read_text().strip():raise RuntimeError('live task controller ownership required')
    # Host PID namespace need not match the container; shared flock must be held.
    for name in ['.controller.lock','.formal-test.lock']:
        with (LOCK_ROOT/name).open('a+') as stream:
            try:fcntl.flock(stream,fcntl.LOCK_EX|fcntl.LOCK_NB)
            except BlockingIOError:pass
            else:raise RuntimeError('expected task controller lock is unowned')
    gateway=None;log=None;events=[];results={};draining=None
    def record(event,**fields):events.append({'at':utc(),'event':event,**fields});atomic_json(root/'capability_events.json',events)
    async with httpx.AsyncClient(trust_env=False,timeout=10) as client:
        async def native_metrics(label):
            summary={}
            for replica in BACKENDS:
                response=await client.get(replica['url']+'/metrics');response.raise_for_status();text=response.text;(root/(label+'_'+replica['id']+'.metrics')).write_text(text)
                values={}
                for key in ['num_requests_running','num_requests_waiting']:
                    matches=re.findall(r'^vllm:'+key+r'(?:\{[^\n]*\})?\s+([0-9.eE+-]+)',text,re.M)
                    if not matches:raise RuntimeError('native request gauge missing: '+key)
                    values[key]=sum(float(x) for x in matches)
                summary[replica['id']]=values
            record(label,metrics=summary);return summary
        async def idle(label,deadline=30):
            end=time.monotonic()+deadline
            while True:
                metrics=await native_metrics(label)
                if all(all(x==0 for x in v.values()) for v in metrics.values()):return
                if time.monotonic()>end:raise RuntimeError('native engine drain unverified')
                await asyncio.sleep(1)
        async def load(name,cases,endpoint):
            directory=root/name;directory.mkdir()
            requests=[]
            for index,(payload,extra) in enumerate(cases):
                path=directory/(str(index)+'.body.json');path.write_text(json.dumps(payload,ensure_ascii=False))
                requests.append({'id':str(index),'body_path':str(path),'arrival_s':index*.04,'timeout_s':180,**extra})
            plan={'kind':'diagnostic','endpoint':endpoint,'requests':requests};atomic_json(directory/'plan.json',plan)
            result=await execute(plan,directory);results[name]=result
            if not result['valid']:raise RuntimeError(name+' request contract failed; inspect native evidence')
            return result
        try:
            await idle('initial')
            if reuse_local:
                identities=[json.loads((Path(reuse_local).parent/(node+'_source.snapshot.json')).read_text()) for node in ['166','167']]
                current=[json.loads((root.parent/(node+'_source.snapshot.json')).read_text()) for node in ['166','167']]
                if any(json.loads(a['stdout'])!=json.loads(b['stdout']) for a,b in zip(identities,current)):raise RuntimeError('local reuse source identity differs')
                for replica in BACKENDS:
                    path=Path(reuse_local)/('local_'+replica['id'])/'load_result.json';data=json.loads(path.read_text())
                    if not data['valid'] or data['effective_output_tokens']!=128:raise RuntimeError('local reuse contract invalid')
                    record('reused_local_full_request',replica=replica['id'],path=str(path),sha256=hashlib.sha256(path.read_bytes()).hexdigest(),limits='native source/config retained; original D firsttoken field missing, remeasured offline; no performance comparison')
            else:
                for replica in BACKENDS:
                    await load('local_'+replica['id'],[(body('Explain request scheduling briefly. '*64),{'expected':{'output_tokens':128}})],replica['url']+'/v1/chat/completions')
            record('local_full_requests_valid')
            env={**os.environ,'GLM_REPLICAS':json.dumps(BACKENDS),'GLM_EXECUTION_GROUPS':(root.parent/'execution_groups.json').read_text(),'GLM_ROUTER_AUDIT_DIR':str(root/'native_wire'),'GLM_ROUTER_TRACE_PATH':str(root/'router_trace.jsonl'),'PYTHONPATH':'/data/tiankuan/wio/Inference-Foundry/glm5-3/runtime'}
            log=(root/'gateway.log').open('wb')
            gateway=subprocess.Popen([sys.executable,'/data/tiankuan/wio/Inference-Foundry/glm5-3/runtime/coupled_gateway.py','--port','8002'],env=env,stdout=log,stderr=subprocess.STDOUT,start_new_session=True)
            record('gateway_started',pid=gateway.pid)
            end=time.monotonic()+15
            while True:
                if gateway.poll() is not None:raise RuntimeError('gateway exited during startup')
                try:
                    response=await client.get(ROUTER+'/healthcheck')
                    if response.status_code==200:break
                except httpx.HTTPError:pass
                if time.monotonic()>end:raise RuntimeError('gateway readiness timed out')
                await asyncio.sleep(.2)
            cases=[
                (body('Give a concrete scheduling example. '*32,128),{'expected':{'output_tokens':128}}),
                (body('A variable load is ',64,completion=True),{'endpoint':ROUTER+'/v1/completions','expected':{'output_tokens':64}}),
                (body('Answer briefly.',16,stream=False),{'expected':{'output_tokens':16}}),
                (body('Give two examples.',16,n=2),{'expected':{'output_tokens':32}}),
                (body('Invalid request',-1),{'expected':{'http_status':400}}),
                (body('Discuss serving variable input and output lengths. '*1024,512),{'expected':{'output_tokens':512}})]
            await load('mixed_open_arrivals',cases,ROUTER+'/v1/chat/completions?glm_contract=capability')
            snapshot=(await client.get(ROUTER+'/control/replicas')).json();record('mixed_completed',snapshot=snapshot)
            declared=json.loads((root.parent/'execution_groups.json').read_text())[0]
            if not all(v['execution_group']==declared['id'] and v['native_owner_epoch']==declared['epoch'] and not v['group_faulted'] for v in snapshot['replicas']):raise RuntimeError('healthy native400 group attribution contract failed')

            if any(r['active_requests'] for r in snapshot['replicas']):raise RuntimeError('completed request lease remained')
            response=await client.delete(ROUTER+'/control/replicas/DP0');response.raise_for_status()
            draining=asyncio.create_task(load('draining_D',[(body('Continue the explanation of capacity. '*32,512),{'expected':{'output_tokens':512}})],ROUTER+'/v1/chat/completions'))
            old_generation=None;end=time.monotonic()+10
            while True:
                snapshot=(await client.get(ROUTER+'/control/replicas')).json();entries=snapshot['replicas']
                if entries and entries[0]['active_requests']>0:old_generation=entries[0]['generation'];break
                if draining.done():await draining;raise RuntimeError('drain request finished before lease observation')
                if time.monotonic()>end:raise RuntimeError('drain lease not observed')
                await asyncio.sleep(.1)
            response=await client.delete(ROUTER+'/control/replicas/DP1');response.raise_for_status();snapshot=response.json();record('drain_started',snapshot=snapshot)
            if not snapshot['replicas'][0]['draining'] or snapshot['replicas'][0]['active_requests']!=1:raise RuntimeError('active drain contract failed')
            response=await client.post(ROUTER+'/control/replicas',json=BACKENDS[0]);response.raise_for_status()
            await load('arrival_during_drain',[(body('Describe admission control.',32),{'expected':{'output_tokens':32}})],ROUTER+'/v1/chat/completions')
            await draining
            snapshot=(await client.get(ROUTER+'/control/replicas')).json()
            if any(r['id']=='DP1' for r in snapshot['replicas']):raise RuntimeError('drained generation remained')
            response=await client.post(ROUTER+'/control/replicas',json=BACKENDS[1]);response.raise_for_status();snapshot=response.json();record('drain_completed_and_readded',snapshot=snapshot)
            if next(r for r in snapshot['replicas'] if r['id']=='DP1')['generation']<=old_generation:raise RuntimeError('generation did not advance')
            payload=body('Explain serving concurrency. '*64,8192);cancel_path=root/'cancel.body.json';atomic_json(cancel_path,payload)
            first=None;cancel_start=time.monotonic()
            async with client.stream('POST',ROUTER+'/v1/chat/completions',json=payload,timeout=httpx.Timeout(connect=10,read=60,write=30,pool=10)) as response:
                response.raise_for_status()
                async for line in response.aiter_lines():
                    if not line.startswith('data:'):continue
                    value=line[5:].strip()
                    if value=='[DONE]':raise RuntimeError('cancel request completed before client cancellation')
                    event=json.loads(value)
                    if any(c.get('delta',{}).get('content') or c.get('delta',{}).get('reasoning_content') or c.get('delta',{}).get('reasoning') for c in event.get('choices',[])):first=value;break
            if first is None:raise RuntimeError('no first content observed for cancellation')
            record('client_closed_after_first_output',first_event=first,elapsed_s=time.monotonic()-cancel_start)
            end=time.monotonic()+30
            while True:
                snapshot=(await client.get(ROUTER+'/control/replicas')).json()
                if not any(r['active_requests'] for r in snapshot['replicas']):break
                if time.monotonic()>end:raise RuntimeError('cancelled lease remained')
                await asyncio.sleep(.1)
            record('cancel_lease_released',snapshot=snapshot)
            await idle('final')
            summary={'run_id':run_id,'kind':'diagnostic','valid':True,'completed_at':utc(),'contracts':['DP0/DP1 coupled local full request','variable open arrivals and output lengths','chat/completion stream/nonstream/native400/n2','active drain and generation readd','client cancellation lease+native engine idle'],'load_results':{k:{f:v[f] for f in ['valid','successful_inference_requests','effective_output_tokens','elapsed_s','effective_tps']} for k,v in results.items()},'cancelled_requests':1,'verdict':'INCONCLUSIVE','limits':['finite capability evidence only; no formal KEEP or stable capacity claim','native implementation retained; expert weight/communication/Graph/cohort deployment changes; no accuracy comparison','tools/multimodal/rare native branches remain covered by compatibility forwarding; not all executed here','effective native config is captured separately in adopted argv/manifest; no performance comparison attributed to router']}
            atomic_json(root/'capability_summary.json',summary);print(json.dumps({'valid':True,'contracts':summary['contracts']}))
        except BaseException as error:
            record('failure',error_type=type(error).__name__,message=str(error));atomic_json(root/'capability_summary.json',{'run_id':run_id,'valid':False,'verdict':'INVALID','error':str(error),'completed_at':utc()});raise
        finally:
            if draining is not None and not draining.done():
                draining.cancel();await asyncio.gather(draining,return_exceptions=True)
            if gateway and gateway.poll() is None:
                os.killpg(gateway.pid,signal.SIGTERM)
                try:gateway.wait(timeout=15)
                except subprocess.TimeoutExpired:os.killpg(gateway.pid,signal.SIGKILL);gateway.wait()
            if gateway:record('gateway_stopped',exit_code=gateway.returncode)
            if log:log.close()
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('root');p.add_argument('run_id');p.add_argument('--reuse-local');a=p.parse_args();asyncio.run(main(a.root,a.run_id,a.reuse_local))
