from pathlib import Path
import json,sys,subprocess,shlex,hashlib,csv
sys.path.insert(0,"/data/tiankuan/wio/Inference-Foundry/glm5-3/runtime")
from phase_runner import atomic_json,utc
j=Path(__file__).parent;p=j.parents[1];idx=json.loads((p/"jobs/REDUCE-PROFILE105-20261002T1934Z/raw_index.json").read_text())
profile=idx["profiles"][0];raw=Path(profile["directory"]);dest=Path("/data/tiankuan/wio/glm52-pd/deploy/private/profile_run105_export_rank0")/raw.name
code="from pathlib import Path;import shutil,sys;src=Path(sys.argv[1]);dst=Path(sys.argv[2]);assert not dst.exists();dst.parent.mkdir(exist_ok=True);shutil.copytree(src,dst);print(str(dst))"
cmd=["ssh","-o","BatchMode=yes","root@172.16.10.167",shlex.join(["python3","-c",code,str(raw),str(dest)])]
z=subprocess.run(cmd,capture_output=True,timeout=120);(j/"copy.stdout").write_bytes(z.stdout);(j/"copy.stderr").write_bytes(z.stderr);z.check_returncode()
shell="source /usr/local/Ascend/ascend-toolkit/set_env.sh; exec /usr/local/Ascend/ascend-toolkit/latest/bin/msprof --export=on --output="+shlex.quote(str(dest))
cmd=["ssh","-o","BatchMode=yes","root@172.16.10.167",shlex.join(["docker","exec","glm52-single","/bin/bash","-c",shell])]
atomic_json(j/"command.json",dict(at=utc(),argv=cmd,raw_source=str(raw),derived_copy=str(dest),NPU_commands=0))
with (j/"export.stdout").open("wb")as out,(j/"export.stderr").open("wb")as err:z=subprocess.run(cmd,stdout=out,stderr=err,timeout=480)
assert z.returncode==0,z.returncode
code="from pathlib import Path;import json,sys,hashlib,csv;root=Path(sys.argv[1]);idx=json.load(sys.stdin);files=[];checks=[]\nfor x in idx:\n f=root/Path(x['path']).relative_to(Path(sys.argv[2]));assert f.stat().st_size==x['bytes'];assert hashlib.sha256(f.read_bytes()).hexdigest()==x['sha256'];checks.append(str(f))\nfor f in root.rglob('*'):\n if not f.is_file()or '/data/'in str(f.relative_to(root))or f.suffix=='.done':continue\n if f.suffix not in ['.csv','.db','.json']:continue\n row=dict(path=str(f),bytes=f.stat().st_size,sha256=hashlib.sha256(f.read_bytes()).hexdigest())\n if f.suffix=='.csv':\n  with f.open()as z:\n   reader=csv.reader(z);row['columns']=next(reader,[]);row['rows']=sum(1 for _ in reader)\n files.append(row)\nprint(json.dumps(dict(raw_copy_hashes_unchanged=len(checks),derived_files=files)))"
orig=[x for x in idx["files"]if Path(x["path"]).is_relative_to(raw)]
z=subprocess.run(["ssh","-o","BatchMode=yes","root@172.16.10.167",shlex.join(["python3","-c",code,str(dest),str(raw)])],input=json.dumps(orig).encode(),capture_output=True,timeout=180);(j/"index.stderr").write_bytes(z.stderr);z.check_returncode();out=json.loads(z.stdout);out.update(at=utc(),source=str(raw),destination=str(dest),actual_export_exit_code=0,limitations=["CPU-only derived rank0 export; no ordinary E2E performance or hardware-bound claim","Other15rank export, common device window and host/device calibration pending"]);atomic_json(j/"reduction.json",out);b=(j/"reduction.json").read_bytes();atomic_json(j/"result.json",dict(schema_version=1,job_id=j.name,status="completed",summary="Run105 rank0 native msprof CPU export completed; copied raw hashes unchanged; derived files indexed, no GPU request",execution=dict(inner_exit_code=0,acceptance="passed",processes=[]),findings=[],evidence=[dict(id="reduction",path=str(j/"reduction.json"),bytes=len(b),sha256=hashlib.sha256(b).hexdigest(),locator="derived export files and source hash coverage")],unknowns=out["limitations"],decision_request=None,next_check_at=None));print(json.dumps(dict(files=len(out["derived_files"]),raw_copy_hashes_unchanged=out["raw_copy_hashes_unchanged"])))
