import json,dataclasses,sys
from coupled_atomic_mq_worker import CoupledAtomicMQWorker
assert CoupledAtomicMQWorker.__bases__[0].__name__=='AtomicMQWorker'
from vllm.engine.arg_utils import EngineArgs
from vllm.config import KVTransferConfig
rows=[]
for role in [sys.argv[1]]:
 for rank in [int(sys.argv[2])]:
  isP=role=="kv_producer"
  transfer=KVTransferConfig(kv_connector="MooncakeConnectorV1",kv_role=role,kv_port=35000 if isP else 35100,engine_id="glm-role-"+role,kv_connector_extra_config={"use_ascend_direct":True,"prefill":{"dp_size":2,"tp_size":16},"decode":{"dp_size":2,"tp_size":16}})
  a=EngineArgs(model="/data/tiankuan/wio/GLM-5.2-w8a8",trust_remote_code=True,quantization="ascend",seed=1024,max_model_len=81933 if isP else 144384,max_num_seqs=1 if isP else 2,max_num_batched_tokens=4096,gpu_memory_utilization=.48,kv_cache_memory_bytes=(1 if isP else 2)*1024**3,tensor_parallel_size=16,decode_context_parallel_size=16,cp_kv_cache_interleave_size=128,prefill_context_parallel_size=1,pipeline_parallel_size=1,data_parallel_size=2,data_parallel_size_local=1,data_parallel_rank=rank,data_parallel_external_lb=True,data_parallel_address="172.16.10.166",data_parallel_rpc_port=35020 if isP else 35120,data_parallel_backend="mp",distributed_executor_backend="mp",enable_expert_parallel=True,nnodes=2,node_rank=rank,master_addr="172.16.10.166",master_port=35030 if isP else 35130,enforce_eager=isP,enable_prefix_caching=True,enable_chunked_prefill=True,compilation_config={"cudagraph_mode":"NONE"if isP else"FULL_DECODE_ONLY"},speculative_config={"num_speculative_tokens":1 if isP else 5,"method":"deepseek_mtp","enforce_eager":True},worker_cls="coupled_atomic_mq_worker.CoupledAtomicMQWorker",kv_transfer_config=None,additional_config={"multistream_overlap_shared_expert":True,"enable_dsa_cp":False,"enable_reduce_sample":False,"enable_fused_mc2":0,"mc2_comm_alg":"hierarchy"})
  c=a.create_engine_config();pc=c.parallel_config
  assert pc.data_parallel_size==2 and pc.tensor_parallel_size==16 and pc.decode_context_parallel_size==16 and pc.world_size_across_dp==32 and pc.local_world_size==16 and pc.enable_expert_parallel
  rows.append({"role":role,"rank":rank,"dp":pc.data_parallel_size,"tp":pc.tensor_parallel_size,"dcp":pc.decode_context_parallel_size,"world":pc.world_size_across_dp,"local_world":pc.local_world_size,"max_model_len":c.model_config.max_model_len,"enforce_eager":c.model_config.enforce_eager,"graph_mode":str(c.compilation_config.cudagraph_mode),"speculative_config":None if c.speculative_config is None else{"K":c.speculative_config.num_speculative_tokens,"method":c.speculative_config.method},"kv_transfer":None if c.kv_transfer_config is None else dataclasses.asdict(c.kv_transfer_config),"kv_memory_bytes":c.cache_config.kv_cache_memory_bytes,"scheduler":{"max_num_seqs":c.scheduler_config.max_num_seqs,"batch_budget":c.scheduler_config.max_num_batched_tokens},"parallel_hash":pc.compute_hash()})
print(json.dumps({"rows":rows,"CPU_only":True,"native_engine_constructed":False,"weights_loaded":0,"model_requests":0,"limits":["Typedconfigs acceptance only; nativeconnector registration/cache/workspace/HCCL actual memory/transport/execution untested","Producerinternalmaxlen81933 proposed; fulluser144384 inputs require source-supportedconsumer localprefill fallback, not yet E2E","Explicit native KV bytes supportedcontrol option, startup/modelLen/cache and workspace runtime guards notbypassed; planned1GiB/2GiB mayfailfit","Combinedcontrolworkerimport only; liveinstallation/roleexecution untested"]}))
