import json,pathlib,hashlib
from vllm.engine.arg_utils import EngineArgs
from vllm_ascend.ascend_config import get_ascend_config
rows=[]
for rank in [0,1,2,3]:
 a=EngineArgs(worker_cls="coupled_dp_worker_v2.CoupledMetadataWorker",model="/data/tiankuan/wio/GLM-5.2-w8a8",trust_remote_code=True,quantization="ascend",seed=1024,max_model_len=144384,max_num_seqs=8,max_num_batched_tokens=16384,gpu_memory_utilization=.80,tensor_parallel_size=8,decode_context_parallel_size=8,prefill_context_parallel_size=1,pipeline_parallel_size=1,data_parallel_size=4,data_parallel_size_local=1,data_parallel_rank=rank,data_parallel_external_lb=True,data_parallel_address="172.16.10.166",data_parallel_rpc_port=32620,data_parallel_backend="mp",distributed_executor_backend="mp",enable_expert_parallel=True,nnodes=1,node_rank=0,master_addr="172.16.10.166",master_port=32630,enable_prefix_caching=True,enable_chunked_prefill=True,compilation_config={"cudagraph_mode":"FULL_DECODE_ONLY"},speculative_config={"num_speculative_tokens":5,"method":"deepseek_mtp","enforce_eager":True},additional_config={"multistream_overlap_shared_expert":True,"enable_dsa_cp":False,"enable_fused_mc2":0,"mc2_comm_alg":"hierarchy"})
 c=a.create_engine_config()
 pc=c.parallel_config
 # Config-only: no LLM/AsyncLLM/EngineCore/worker constructed.
 rows.append({"rank":rank,"worker_cls":pc.worker_cls,"parallel_hash":pc.compute_hash(),"world":pc.world_size_across_dp,"local_world":pc.local_world_size,"model_architectures":c.model_config.architectures,"max_model_len":c.model_config.max_model_len,"max_num_batched_tokens":c.scheduler_config.max_num_batched_tokens,"max_num_seqs":c.scheduler_config.max_num_seqs,"kv_transfer_config":None if c.kv_transfer_config is None else str(c.kv_transfer_config),"additional_config":c.additional_config,"num_speculative_tokens":c.speculative_config.num_speculative_tokens,"graph_mode":str(c.compilation_config.cudagraph_mode)})

assert len(rows)==4 and all(row["world"]==32 and row["local_world"]==8 and row["kv_transfer_config"] is None and row["num_speculative_tokens"]==5 and row["worker_cls"]=="coupled_dp_worker_v2.CoupledMetadataWorker" for row in rows)
assert len(set(row["parallel_hash"]for row in rows))==1
print(json.dumps({"accepted_config_only":True,"configurations":rows,"physical_plan":{"hosts":2,"NPUs_per_host":16,"DP_engines_per_host":2,"NPUs_per_engine":8,"EP_total":32,"native_nnodes_semantics":"one node within each explicitly external DP engine; physical hosts still two","device_placement":"two disjoint8-device slices perhost required, not liveproven"},"model_requests":0,"weights_loaded":0,"EngineCore_or_worker_created":False,"limitations":["Native EngineArgs only; no fit/collective/Graph/metadata4rank/nativefunction/performance proof","Explicit unique device placement/APIports/superpod IDs/HCCL groups required before anynativeexecution","Alternative32NPUs layout, not queued or preclaimed gain"]}))
