#ifndef RUNTIME_VERSION_H
#define RUNTIME_VERSION_H

#define RUNTIME_VERSION_STR "9.1.0"
#define RUNTIME_MAJOR 9
#define RUNTIME_MINOR 1
#define RUNTIME_PATCH 0
#define RUNTIME_PRERELEASE ""
#define RUNTIME_VERSION_NUM ((9 * 10000000) + (1 * 100000) + (0 * 1000))

#endif /* RUNTIME_VERSION_H */
